### ISSUE TITLE
TODO notes

### ISSUE THREAD

**Issue by ProditorMagnus** [ProditorMagnus/OrociaRandomMod#5]
- [ ] https://github.com/wesnoth/wesnoth/issues/9675 indicates that [modify_unit] is not allowed to change movecost anymore https://github.com/ProditorMagnus/OrociaRandomMod/blob/master/utils/wave_modifications.cfg#L36
- [ ] wave delaying doesnt update wave composition labels
- [ ] test if nonageless waves work when ageless is not installed
- [ ] if not generating waves for side, remove their village too
- [ ] #4 remove leader
- [ ] https://forums.wesnoth.org/viewtopic.php?p=647894#p647894 poison saves
- [ ] Use hex values for objectives colors
- [ ] Healer list generation and verification
- [ ] Check if perfect drone needs to be moved to level 3 list.
- [ ] Reduce ultra hardcore charge base value
- [ ] Check ultra hardcore 31 and 33 secondary bonus base values
- [ ] Increase bonusspam adr modifier, like max(x^constant1, x+constant2), initial idea (2, 0.5)
- [ ] Use set_side_id for ai color
- [ ] With hp multiplier units start with hp that is not their max hp
- [ ] Do something to discourage blocking observers, like invisible enemies, no labels, no upgrades info - removing those tags
- [ ] Consider choosing random spawns before the turn and displaying them
- [x] Unlist kamikaze
- [x] Menu to pause waves for one turn - increase turn number of everything following
- [x] Try endless mode
- [x] unlist level 4 nordhris units and AE_rhy_dw_Scorpio and AE_rhy_dw_Ballista
- [x] reloading is broken

**Comment by ProditorMagnus** [comment]
- [ ] Update ultra hardcore description now that someone has beaten it (Caleb123)
[ORM ultra hardcore won.gz](https://github.com/ProditorMagnus/OrociaRandomMod/files/2567578/ORM.ultra.hardcore.won.gz)
- [ ] ultra hardcore could add message asking winner to share the replay
